.TH dmenu-emoji 1
.
.SH NAME
.
dmenu-emoji \- graphical emoji selector
.
.SH SYNOPSIS
.
.SY dmenu-emoji
.
.SH DESCRIPTION
.
.B dmenu-emoji
shows a list of all emojis through
.IR dmenu (1)
and copies the selected emoji to the clipboard.  On X11 this requires
.IR xclip (1)
and on wayland this requires
.IR wl-copy (1).
.
.SH SEE ALSO
.
.IR xclip (1),
.IR wl-copy (1).
