.TH healthy-legs 1
.
.SH NAME
.
healthy-legs \- remind user to stretch their legs
.
.SH SYNOPSIS
.
.SY healthy-legs
.RI [ time\fR]\fP
.
.SH DESCRIPTION
.
The
.B healthy-legs
program sleeps for a specified amount of time (one hour by default) and then
shows a desktop notification to remind the user to get up and stretch their
legs.
.
.PP
The
.I time
argument is passed directly into
.IR sleep (1)
and therefore supports the same format.
