.TH healthy-legs 1
.
.SH NAME
.
healthy-legs \- remind user to stretch their legs
.
.SH SYNOPSIS
.
.SY healthy-legs
[\fItime\fP]
.
.SH DESCRIPTION
.
The
.B healthy-legs
program sleeps for a specified amount of time (one hour by default) and then
shows a desktop notification to remind the user to get up and stretch their
legs.
.
.PP
The
.I time
argument uses the same format as
.IR sleep (1).
