.TH wname 1
.
.SH NAME
.
wname \- print name of the current window
.
.SH SYNOPSIS
.
.SY wname
.
.SH DESCRIPTION
.
.B wname
prints the name (i.e.\& the window title) of the active X window.
.
.PP
It is meant to be used in status bars of window managers that do not provide
this information themselves (e.g.\& OpenBSD's
.IR cwm (1)).
